### ISSUE TITLE
Return element as prop

### ISSUE THREAD

**Issue by Ehesp** [rehypejs/rehype-react#12]
Hey

No clue if this is possible... However is the following do-able?

```js
// components
import Card from './Card';
import Icon from './Icon';

// types
{
  card: Card,
  icon: Icon,
}
```

The following works fine:

```md
<card title="Getting Started">
  New to React Native Firebase? Learn how to get started with our detailed guides.
</card>

<icon icon="user"></icon>
```

Now is it possible to pass an element as a property of another? e.g:

```md
<card 
  title="Getting Started"
  icon="<icon icon='user'></icon>"
>
  New to React Native Firebase? Learn how to get started with our detailed guides.
</card>
```

Now on my card component, the `icon` prop is a React Element I can render?

Cheers

**Comment by wooorm** [comment]
You could use a parent component for that, such as `CardWithIcon`.
Parsing attributes is outside the scope of this package.
