### ISSUE TITLE
Access frontmatter variable in markdown

### ISSUE THREAD

**Issue by master12** [rehypejs/rehype-react#14]
Can we add a feature that we can access the frontmatter variables in markdown and pass them as property of a component?

Example:

```
---
title: Fake Title
---
<title-component text={{ frontMatter.title }} ></title-component>

and

<title-component>{{ frontMatter.title }}</title-component>
```

Similar to this lib:
https://github.com/hugmanrique/react-markdown-loader

Thanks

**Comment by wooorm** [comment]
Functionality such as that could be attained with [MDX](https://github.com/mdx-js/mdx).
