### ISSUE TITLE
Example for custom component

### ISSUE THREAD

**Issue by Ciantic** [rehypejs/rehype-react#15]
The example should include a way to use components. I found out how to do it, I needed a raw as well as allowing dangerousHTML, but it's not perhaps obvious for new comers.

```typescript
    import raw from "rehype-raw";

    const Test = (props: any) => {
        return <div>custom component</div>;
    };
    unified()
        .use(markdown, {
            commonmark: true
        })
        .use(remark2hype, { allowDangerousHTML: true }) // THIS is required
        .use(raw)  // THIS is also required
        .use(rehype2react, {
            createElement: React.createElement,
            components: {
                test: Test // Notice that rehype lowercases all HTML elements
            }
        })
        .processSync("your input here").contents;
```

**Comment by tobytraylor** [comment]
Thanks for this.  The articles i read omitted the use of raw.  Wasted a few hours on this bad boy.

**Comment by johnatspreadstreet** [comment]
> The example should include a way to use components. I found out how to do it, I needed a raw as well as allowing dangerousHTML, but it's not perhaps obvious for new comers.
> 
> ```ts
>     import raw from "rehype-raw";
> 
>     const Test = (props: any) => {
>         return <div>custom component</div>;
>     };
>     unified()
>         .use(markdown, {
>             commonmark: true
>         })
>         .use(remark2hype, { allowDangerousHTML: true }) // THIS is required
>         .use(raw)  // THIS is also required
>         .use(rehype2react, {
>             createElement: React.createElement,
>             components: {
>                 test: Test // Notice that rehype lowercases all HTML elements
>             }
>         })
>         .processSync("your input here").contents;
> ```

Thanks @Ciantic , saved me a few hours of hell.

**Comment by wooorm** [comment]
While `rehype-raw` works, IT IS A SECURITY RISK AND NOT GOOD FOR BROWSERS! If you’re going to potentially throw security and bundle size out of the window, then please folks, read the readmes and spend the hours thinking about it!

**Comment by tomtobac** [comment]
> While `rehype-raw` works, IT IS A SECURITY RISK AND NOT GOOD FOR BROWSERS! If you’re going to potentially throw security and bundle size out of the window, then please folks, read the readmes and spend the hours thinking about it!

I couldn't find any reference in the docs, and this issue was the only way to help me. What is the recommended way? Thank you

**Comment by wooorm** [comment]
Hey! Please ask questions through the designated support channels: https://github.com/rehypejs/.github/blob/main/support.md, thanks.
Issues are about problems in this project. Old closed issues are about old problems that don’t exist anymore.
