### ISSUE TITLE
Typings for typescript projects

### ISSUE THREAD

**Issue by andrezero** [rehypejs/rehype-react#16]
Just starting using unified, remark & rehype in the context of a static site generator written in typescript and noticed this package is missing typings.

I just patched it with the following local `src/node_modules/rehype-react/index.d.ts`, which is enough for my project but would be great to have complete typings for this plugin.
```
// TypeScript Version: 3.0

declare module 'rehype-react' {
  import { Plugin } from 'unified';

  const rehype2react: Plugin;

  export default rehype2react;
}
```

**Comment by wooorm** [comment]
I suggest adding types to definitely typed. That’s what TS itself suggests for modules not written in TypeScript.
