### ISSUE TITLE
Fail to run the example after upgrading to 4.0.0

### ISSUE THREAD

**Issue by nkCoding** [rehypejs/rehype-react#18]
### Subject of the issue

After upgrading rehype-react to 4.0.0, the first example in README fails. The `contents` renders nothing.

It produces expected html string by replacing `.use(rehype2react, {createElement: React.createElement})` with `.use(rehypeStringify)`. So I think it's on rehype-react.

Rehype-react 3.1.0 works fine.

I'm testing it in a next.js page and I'll downgrade it for now.

### Your environment

*   **Packages**: 
```
{
    "next": "^9.0.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "rehype-highlight": "^3.0.0",
    "rehype-react": "^4.0.0",
    "rehype-stringify": "^6.0.0",
    "remark-parse": "^6.0.3",
    "remark-rehype": "^4.0.1",
    "remark-slug": "^5.1.2",
    "remark-toc": "^5.1.1",
    "unified": "^8.1.0"
}
```

### Steps to reproduce

Run the example provided by README in the latest next.js env. (Haven't tested it in other environments)

### Expected behaviour

Return react components in `contents`.

### Actual behaviour

Return nothing.

**Comment by wooorm** [comment]
Thanks for reporting this! For some reason this bug snuck through the tests!

**Comment by wooorm** [comment]
Released!
