### ISSUE TITLE
node array property value is serialized

### ISSUE THREAD

**Issue by karaxuna** [rehypejs/rehype-react#23]
### Steps to reproduce

See: https://github.com/syntax-tree/hast-to-hyperscript/issues/18

### Expected behavior

Should pass unchanged properties to react comoponent.

### Actual behavior

Serializes array property with `value.join(' ')`.

**Comment by wooorm** [comment]
I don’t think it should. The issue you reference is closed for a reason. If you don’t supply more information, the answer is the same.

**Comment by karaxuna** [comment]
@wooorm please, help me understand why I shouldn't be able to pass array as a property value to **react** component? I understand the reason for html.

**Comment by ChristianMurphy** [comment]
@karaxuna the format that is being used as a source is hast (HTML Abstract Syntax Tree).
It is designed to be a representation of HTML, nothing more.

If you need to represent JSX features, like array props, consider using another unified+remark project mdx https://github.com/mdx-js/mdx
Which has an extended abstract syntax tree to represent JSX https://mdxjs.com/advanced/ast

**Comment by karaxuna** [comment]
@ChristianMurphy thank you!
