### ISSUE TITLE
Incorrect TypeScript typings

### ISSUE THREAD

**Issue by Ry7n** [rehypejs/rehype-react#24]
I'm working from the Gatsby [guide for using Rehype](https://using-remark.gatsbyjs.org/custom-components/), and the code examples from the guide are failing in the TypeScript compiler using `typescript@3.8.3`:

```ts
import rehypeReact from "rehype-react";

const renderAst = new rehypeReact({
  createElement: React.createElement,
  components: {},
}).Compiler;
```

Fails with: `Only a void function can be called with the 'new' keyword.ts(2350)`

Removing `new` doesn't help:

```ts
const renderAst = rehypeReact({
  createElement: React.createElement,
  components: {},
}).Compiler;
```

Fails with: `Property 'Compiler' does not exist on type 'Transformer'.ts(2339)`.

Looking at the code, it looks like this code example _should_ work.

I think the typing you want might be something like:

```
declare class rehypeReact<H extends CreateElementLike> {
  constructor(options: rehypeReact.Options<H>);
  Compiler: Transformer
}
```

If you'd accept it, I can try my hand at a PR to fix the typings.

**Comment by wooorm** [comment]
Oh my gosh. What is gatsby suggesting there?!

The types here are correct. The example in the readme here is correct. What gatsby is suggesting there is really weird.

**Comment by wooorm** [comment]
Closing this because they are suggesting weird things and it’s not something we should fix.

**Comment by YutaUra** [comment]
This works.

```tsx
import { createElement } from "react"
import rehypeReact from "rehype-react"
import unified from "unified"

const processor = unified().use(rehypeReact, {
  createElement,
  components: {
    p: (props) => <SomeParagraph {...props} />,
  },
})

export const renderAst = (ast: any): JSX.Element => {
  return (processor.stringify(ast) as unknown) as JSX.Element
}
```
