### ISSUE TITLE
Invalid typing on options -> components

### ISSUE THREAD

**Issue by ignatiusreza** [rehypejs/rehype-react#25]
### Subject of the issue

I would like to overrides some of the components with custom ones.

The typing provided for `components` doesn't seems to be compatible with `FC`..

### Your environment

*   **OS**: Ubuntu 20.04
*   **Packages**: `"rehype-react": "^6.1.0"`, `"@types/react": "^17.0.0"`,  and other `remark` and `rehype` packages which shouldn't affect the related typing
*   **Env**: n/a

### Steps to reproduce

```tsx
import {
  ComponentType,
  FC,
  Fragment,
  ReactElement,
  createElement,
} from 'react';
import parse from 'remark-parse';
import rehype from 'remark-rehype';
import render from 'rehype-react';
import sanitize from 'rehype-sanitize';
import unified from 'unified';

const MyLink: FC = () => null;

interface MarkdownProps {
  children: string;
}

const Markdown: FC<MarkdownProps> = ({ children, components }) =>
  unified()
    .use(parse)
    .use(rehype)
    .use(sanitize)
    .use(render, {
      components: { a: MyLink },
      createElement,
      Fragment,
    })
    .processSync(children).result as ReactElement;

export default Markdown;
```

### Expected behavior

No typing errors

### Actual behavior

Typing errors is reported for `components`

> Type 'FC<{}>' is not assignable to type 'ComponentLike<ReactElement<{}, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>>'. Types of parameters 'props' and 'props' are incompatible. Type 'ComponentProps' has no properties in common with type '{ children?: ReactNode; }'.

**Comment by ChristianMurphy** [comment]
@ignatiusreza the types are correct, you can see the tests for them and working examples in
https://github.com/rehypejs/rehype-react/blob/39d517894a69157224f96a830055884340d3fbca/types/rehype-react-test.tsx#L32-L57

The error you are seeing reflects that `children` is not guaranteed to be `string`, it is `unknown` until it is narrowed, so the types are incompatible.
To narrow the type consider something like:

```typescript
const functionComponent: React.FunctionComponent<rehypeToReact.ComponentProps> = ({children}) => {
  if (typeof children === 'string') {
    return null; // do something with string
  }
  return null; // fallback otherwise
}

unified().use(rehypeToReact, {
  createElement: React.createElement,
  components: {
    div: functionComponent
  }
})
```

**Comment by ignatiusreza** [comment]
@ChristianMurphy thanks for the reply..

I opened a PR with failing examples before reading the edited comment.. :sweat_smile: 

Typing the component with `React.FunctionComponent<rehypeToReact.ComponentProps>` does work for functional component :+1: 

but it doesn't work when using class component, even with `React.Component<rehypeToReact.ComponentProps>`..

and, while the example was written in a simplified manner, in reality, most of the components that I would like to override comes from `@material-ui/core`, on which I have no control on how they defined the typing for the component Props..

**Comment by ChristianMurphy** [comment]
`React.Component<rehypeToReact.ComponentProps>` I see :thinking: 

Some context, `rehype-react` is general to hyperscript compatible languages, not just React but also Vue, VirtualDOM, etc.
The types are generalized with

https://github.com/rehypejs/rehype-react/blob/39d517894a69157224f96a830055884340d3fbca/types/index.d.ts#L15

to allow the typings of each framework to be compatible.
function components are fairly consistent across the board, allowing generics to work fairly well.
class components tend to be more framework specific, it may be possible to generalize, but my gut feeling is it could get messy and complex fast.

> components that I would like to override comes from `@material-ui/core`, on which I have no control on how they defined the typing for the component Props

An example may help me better understand exactly what your ideal syntax/mapping would look like.
At a general level, without seeing that ideal, it could make sense to add wrappers around the MUI components.

https://github.com/rehypejs/rehype-react/blob/39d517894a69157224f96a830055884340d3fbca/types/index.d.ts#L10-L13

is indexed for a reason, rehype or a plugin can add pretty much any attribute, and there is a change that attribute could override/conflict with MUI in an unexpected and undesired way.

an alternative would be a function wrapper
```typescript
unified().use(rehypeToReact, {
  createElement: React.createElement,
  components: {
    div: ({children}) => <SomeMuiClassComponent>{typeof children === 'string' ? children : null}</SomeMuiClassComponent>
  }
})
```

**Comment by ignatiusreza** [comment]
I see, thanks for the extra context!

If we can make it work by default for functional component, that would be great.. having to add a wrapper around class component is acceptable for me but, I guess we should write it down in readme?

anyway, I updated the PR to also include a potential fix for functional component case.. and it is passing with the added test case.. I've also check the updated typing in my project, and it is working as expected..
