### ISSUE TITLE
custom component with nesting

### ISSUE THREAD

**Issue by majiang** [rehypejs/rehype-react#27]
I'm using [react-remark](https://github.com/remarkjs/react-remark) and trying to use a custom component to render [generic directives for remark](https://github.com/remarkjs/remark-directive).  My `useRemark` call is like the following:

```ts
useRemark(
{
    remarkPlugins:
    [
        remarkDirective,
        remarkGfm,
        remarkMath,
    ],
    remarkToRehypeOptions:
    {
        handlers:
        {   // custom handler for directives which derives `tagName` from `node.name` and other properties
            textDirective: handler,
            leafDirective: handler,
            containerDirective: handler,
        },
    },
    rehypePlugins:
    [
        rehypeKatex,
    ],
    rehypeReactOptions:
    {
        myComponents
    }
})
```

where the values of `myComponents` are usual React components, which can have `children: ReactNode[]` and other `prop`s.  Like [in `mdast-util-to-hast/lib`](https://github.com/syntax-tree/mdast-util-to-hast/tree/main/lib) there should be some means to handle nesting by recursively process the `props` (including `children`) and then pass them to `createElement`.  Ho can I achieve this?

**Comment by ChristianMurphy** [comment]
> there should be some means to handle nesting by recursively process the `props`

Can you expand on what you mean by this?
An input-output pair, with some context on what needs to be recursive, could help illuminate the question/concern.

**Comment by majiang** [comment]
Say I have

```md
::::: mydirective1 [inline-content with *em* and **strong**]
1. contents can have  *em* and **strong** too
2. contents can have :mydirective2 (without inline-content by default)

:::important
# usual markdown header here also
:::
:::::
```

and would like something like

```tsx
<MyDirective1 inlineContent={<>inline-content with <em>em</em> and <strong>strong</strong>}>
<ol>
<li>contents can have <em>em</em> and <strong>strong</strong> too</li>
<li>contents can have <MyDirective2 /> (without inline-content by default)</li>
</ol>
<Important>
<h1>usual markdown header here also</h1>
</Important>
</MyDirective1>
```

**Comment by majiang** [comment]
Reopening because closed by accident.

According to my current understanding, I have no access to the converted-to-react children and other props when creating parent.

**Comment by ChristianMurphy** [comment]
>  I have no access to the converted-to-react children and other props when creating parent.

Are props, like: https://github.com/rehypejs/rehype-react/blob/7c60ebeddcdd4ade6848204b16ae1d775fa6072d/test.js#L114-L117
what you are looking for?

**Comment by majiang** [comment]
My problem may be with `remarkToRehypeOptions.handlers`.  After some try and error, my `handler` and component are now like:

```ts
function handler(h: H, node: Node): Node
{
    // first element of children is the label for directive (data.directiveLabel = true).
    // extract the label and transform.
    const label = one(h, (node.children as Node[]).shift()!, node)
    // transform remaining children.
    return h(node, 'myelementname', {label: label}, all(h, node))
}

function Component(props:
{
    label: any, // should be: React.ReactNode
    children: React.ReactNode[],
})
{
    return <div><p>label: {props.label}</p><div>children: {props.children}</div></div>
}
```

where `all` and `one` is imported from [mdast-util-to-hast/lib](https://github.com/syntax-tree/mdast-util-to-hast/tree/main/lib).

`rehype-react` takes care of the transformation for `props.children` recursively, but not `props.label`.  Namely, `props.label` is a `hast` `Node`.  How can I specify the transformation of this to `ReactNode`?

**Comment by ChristianMurphy** [comment]
hast/rehype expects all children to be part of the `children` prop.
You can transform `props.label` into a node, but you'd have to call the method directly.
Or you could move the label to `children`.

**Comment by majiang** [comment]
Thank you for explanation!  I understood that it is a natural limitation I can workaround by moving everything into `children` that should be recursively transformed.
