### ISSUE TITLE
Tags don't change after implementation rehype-react option (options.components)

### ISSUE THREAD

**Issue by teinett** [rehypejs/rehype-react#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^7.0.2

### Steps to reproduce

I use Next.js and Strapi for my blog. Strapi sends markdown for post's content.

I use the latest packages from npm:
- "next": "^11.1.2",
- "react": "^17.0.2",
- "react-dom": "^17.0.2",
- "unified": "^10.1.0",
- "remark-parse": "^10.0.0",
- "remark-rehype": "^9.0.0",
- "rehype-react": "^7.0.2",

**I would like to change <a> link to <Link> component if it's a local link.**
I used the article https://dev.to/jameswallis/how-to-use-the-remark-markdown-converters-with-next-js-projects-a8a as a source.

File components/CustomLink.js:

```javascript
import Link from 'next/link';

function CustomLink({ children, href }) {

    console.log('CustomLink applied');

    return href.startsWith('/') || href === '' ? (
        <Link href={href}>
            <a>
                {children}
            </a>
        </Link>
    ) : (
        <a href={href} target="_blank" rel="noopener noreferrer">
            {children}
        </a>
    );
}

export default CustomLink;
```

File components/PostMarkdown.js

```javascript
import React from 'react';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remark2rehype from 'remark-rehype';
import rehype2react from 'rehype-react';
import CustomLink from 'components/CustomLink';
import styles from './PostMarkdown.module.css';

const PostMarkdown = ({ fulltext }) => {

    const mdtextTransformed = unified()
        .use(remarkParse)
        .use(remark2rehype)
        .use(rehype2react, {
            createElement: React.createElement,
            сomponents: {
                a: CustomLink, 
                // a: (props) => <CustomLink {...props} />,
            },
        })
        .processSync(fulltext)
        .result;

    return (
        <div itemProp="articleBody" className={styles.content}>
            {mdtextTransformed}
        </div>
    );
};

export default PostMarkdown;

```

### Expected behavior

The link <a> is replaced by the component <Link> in the post body in the correct places. 

### Actual behavior

The problem is in the part:

```javascript
сomponents: {
   a: CustomLink, 
   // a: (props) => <CustomLink {...props} />,
},
```

in the code:

```javascript
.use(rehype2react, {
            createElement: React.createElement,
            сomponents: {
                a: CustomLink, 
                // a: (props) => <CustomLink {...props} />,
            },
        })
```

The code works the same with and without part of "components":

```javascript
.use(rehype2react, {
            createElement: React.createElement,
        })
```

I tried both variants with 0 result: 
- a: CustomLink, 
- a: (props) => <CustomLink {...props} />

For example, **I expected to see the part `target="_blank" rel="noopener noreferrer"` in the external link, but it's not there:**

![2021-09-17 22-31-06](https://user-images.githubusercontent.com/1038168/133844766-cffb5ff7-173b-4331-be8b-08fd914fe6f6.jpg)

### Runtime

Node v14

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Next.js

**Comment by teinett** [comment]
Some magic happened: I used https://github.com/tgiv014/mntn/blob/main/components/Markdown.js as an example, and it worked!

**Comment by wooorm** [comment]
Glad it works!
Should `<a>` be inside Next’s` `<Link>` though? I don’t know much about how Next work but it seems weird?
