### ISSUE TITLE
Type declarations broken

### ISSUE THREAD

**Issue by jaens** [rehypejs/rehype-react#34]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.2

### Steps to reproduce

Compile the following TypeScript:

```typescript
import rehype_react from "rehype-react";
```

### Expected behavior

It compiles.

### Actual behavior

There's a compile error:
```
node_modules/rehype-react/index.d.ts:4:28 - error TS7016: Could not find a declaration file for module './lib/index.js'. 'node_modules/rehype-react/lib/index.js' implicitly has an 'any' type.

4 import type {Options} from './lib/index.js'
```

Looks like something is missing, there are no type declarations (`*.d.ts`) in `lib/` for the compiled `./lib/index.js` file that is being `import`ed.

### Runtime

Node v16

### Package manager

yarn v1

### OS

Linux

**Comment by jaens** [comment]
Looks like the `lib/*.d.ts` are missing from the currently published npm version for some reason.
Built locally with `npm pack`, they do get included in the tarball.

**Comment by wooorm** [comment]
thanks for reporting, fixed!
