### ISSUE TITLE
Allow for props on custom react components

### ISSUE THREAD

**Issue by lukasoppermann** [rehypejs/rehype-react#35]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When using custom elements I need to set properties on them, e.g.

```js
    .use(rehype2react, {
      createElement: React.createElement,
      components: {
        h5: Headline, // <Headline level="5">,
        p: Paragraph
      }
    })
```

### Solution

Allow setting properties for custom elements either by passing some kind of object or maybe via a function?

```js
    .use(rehype2react, {
      createElement: React.createElement,
      components: {
        h5: (children) => <Headline level="5">{children}</Headline>,
        p: Paragraph
      }
    })
```

### Alternatives

Idk, please advise if this can be solved differently.

**Comment by wooorm** [comment]
Have you tried your proposed solution? That should work! Because that’s a component too!

**Comment by lukasoppermann** [comment]
Nice, I mis-interpreted an error message and thought it was because it wasn't supported, works like a charm, thanks.
