### ISSUE TITLE
Support React 18 types

### ISSUE THREAD

**Issue by skirsten** [rehypejs/rehype-react#39]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.4

### Steps to reproduce

- Use `@types/react@^18.0.3`
- Pass `createElement: React.createElement, Fragment: React.Fragment` to rehype-react.

### Expected behavior

No type errors

### Actual behavior

Type error

```
Type error: Argument of type '[{ createElement: { (type: "input", props?: (InputHTMLAttributes<HTMLInputElement> & ClassAttributes<HTMLInputElement>) | null | undefined, ...children: ReactNode[]): DetailedReactHTMLElement<...>; <P extends HTMLAttributes<...>, T extends HTMLElement>(type: keyof ReactHTML, props?: (ClassAttributes<...> & P) | ... ...' is not assignable to parameter of type '[boolean] | [Options]'.
  Type '[{ createElement: { (type: "input", props?: (InputHTMLAttributes<HTMLInputElement> & ClassAttributes<HTMLInputElement>) | null | undefined, ...children: ReactNode[]): DetailedReactHTMLElement<...>; <P extends HTMLAttributes<...>, T extends HTMLElement>(type: keyof ReactHTML, props?: (ClassAttributes<...> & P) | ... ...' is not assignable to type '[boolean]'.
    Type '{ createElement: { (type: "input", props?: (React.InputHTMLAttributes<HTMLInputElement> & React.ClassAttributes<HTMLInputElement>) | null | undefined, ...children: React.ReactNode[]): React.DetailedReactHTMLElement<...>; <P extends React.HTMLAttributes<...>, T extends HTMLElement>(type: keyof React.ReactHTML, props?...' is not assignable to type 'boolean'.

  50 |     () =>
  51 |       unified()
> 52 |         .use(rehypeReact, {
     |                           ^
  53 |           createElement: React.createElement,
  54 |           Fragment: React.Fragment,

```

### Runtime

Node v16

### Package manager

pnpm

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Probably a good idea!

**Comment by wooorm** [comment]
done!

**Comment by skirsten** [comment]
Thanks for fixing this so quickly! Can confirm, no more type errors :tada:

**Comment by Mitsunee** [comment]
Currently getting similar error with `@types/react@18.0.25` and `rehype-react@7.1.1`. Using `// @ts-ignore` for now as I know it currently works, but I'd really like to typecheck the rest of my Options.

**Comment by ChristianMurphy** [comment]
@Mitsunee it works with latest `@types/react` and `rehype-react` in a sandbox.
https://codesandbox.io/s/rehype-react-types-b5pe22?file=/src/App.tsx

If you are seeing an issue, please create a reproducible example and open a new issue with details.
