### ISSUE TITLE
Nested @types/react dependency is conflicting with main project dependency

### ISSUE THREAD

**Issue by joshuabradley012** [rehypejs/rehype-react#40]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.0

### Steps to reproduce

- Add `react` `16.14.0`
- Add `@types/react` `17.0.11`
- Add `react-rehype` `7.1.0`
- Ensure typescript is installed globally `npm install typescript -g`
- Run `tsc --project . --pretty`
- Observe the type errors

A discussion of similar issues appears [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20350).

The top suggestion is to move type dependencies to `peerDependencies` allowing yarn to resolve the correct version.

### Expected behavior

There should be no conflicts with the existing react types.

### Actual behavior

There are hundreds of typescript errors anywhere react is installed.

### Runtime

Node v14

### Package manager

yarn 3

### OS

Linux

### Build and bundle tools

Webpack, Create React App

**Comment by wooorm** [comment]
Could you check whether a peer dependency makes it work?

**Comment by joshuabradley012** [comment]
It does. Moving @types packages to peerDependencies resolves the conflict with react types.

https://github.com/joshuabradley012/rehype-react/commit/f181ea12fa2a15d9b68449a6c0722ff57d90fb2e

**Comment by ChristianMurphy** [comment]
@joshuabradley012 there may be some deeper issues.
From your description:

* You are using version 16 of react
* You installed the types from version 17 of react
* This package expects types from version 18

Three different major versions of React and its typings living together 😅 

Even if we made this a peer dependency, there would still be a likely be version conflict.
If you are using yarn 3, as mentioned in the issue description that issue would likely happen at install time, due to an unsatifiable version constraint. (and if it doesn't that is likely a bug in yarn)

If `rehype-react` intends to support previous versions of React, the version range would likely need to be widened to something like `^17.0.0 || ^18.0.0`.

**Comment by joshuabradley012** [comment]
@ChristianMurphy you're right, the project is messy.

However, you are dismissing my comment. The change I made to move type packages to peer dependencies works. The type errors are gone, there is no yarn error.

Further, this is the exact use case for peer dependencies. Node [created this convention specifically for plugins](https://nodejs.org/en/blog/npm/peer-dependencies/).

So, without attacking my project, or dismissing my findings, why do you not want to make this change?

**Comment by ChristianMurphy** [comment]
I'm noting that the change you've made, by itself, _may_ work in yarn 3 _now_, **but** will not work in other package managers (including other versions of yarn, potentially even future versions of yarn 3).

Again, package managers act as constraint solvers.
Yarn 3 allowing a version of types react which is outside of the allowed range may be how it is implemented today, but it would be a mistake to rely on that.
The versions which are supported should be directly noted in the version range, and if version 17 is one of them, it should be in the version range.

In your example (https://github.com/joshuabradley012/rehype-react/commit/f181ea12fa2a15d9b68449a6c0722ff57d90fb2e) react 17 is not in range, only react 18 is in range.
In addition, the other types packages should not be moved to `peerDepedencies`

**Comment by joshuabradley012** [comment]
Oh nice, you closed the thread.

**Comment by joshuabradley012** [comment]
Look I understand there are complexities here that I don't have the context to understand. And maybe this package is built to only work for React 17+, which is fine, author's choice.

All I know is, the project I am on uses hundreds of packages without issue. This is the only package that causes conflicts with existing type definitions. That indicated to me that something was wrong that should be fixed. I did due research to give you an idea of where to look, and left it at that.

In return, you, the author's of this package, have been dismissive and passive aggressive. It's insulting and infuriating. I found a real issue, suggested a fine solution, and got completely shut down.

Improve the package if you'd like. But please, be kinder to the dev community.

**Comment by wooorm** [comment]
This is closed because I fixed it. If it isn't fixed for you, explain what doesn't work for you. You dont get to be annoyed at free shit here.

**Comment by joshuabradley012** [comment]
My bad. I missed your change, my complaint was undue. Thank you for making that update. There are remaining typescript issues, but they are not related to React. I will do some discovery and open a ticket if I find a solution.
