### ISSUE TITLE
srcSet on the picture element is generated disabling the responsive images

### ISSUE THREAD

**Issue by yathomasi** [rehypejs/rehype-react#41]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.4~latest

### Link to runnable example

https://codesandbox.io/s/gatsby-starter-blog-rehype-react-95q31j?file=/src/templates/blog-post.js

PS: I have also logged srcSet to console. It's an array that I believe is the expected srcSet type for the rehype.

### Steps to reproduce

Adding react-rehype to the existing https://github.com/gatsbyjs/gatsby-starter-blog.

### Expected behavior

srcset with comma
```html
<source srcset="/static/8058f3f26913fea3b6a89a73344fe94a/e10e9/salty_egg.webp 158w, /static/8058f3f26913fea3b6a89a73344fe94a/7600a/salty_egg.webp 315w, /static/8058f3f26913fea3b6a89a73344fe94a/d869c/salty_egg.webp 630w, /static/8058f3f26913fea3b6a89a73344fe94a/38d5d/salty_egg.webp 945w, /static/8058f3f26913fea3b6a89a73344fe94a/4eefe/salty_egg.webp 1260w, /static/8058f3f26913fea3b6a89a73344fe94a/7c4f2/salty_egg.webp 2048w" sizes="(max-width: 630px) 100vw, 630px" type="image/webp">
```

### Actual behavior

It's generating srcSet without comma
```html
<source srcset="/static/8058f3f26913fea3b6a89a73344fe94a/e10e9/salty_egg.webp 158w /static/8058f3f26913fea3b6a89a73344fe94a/7600a/salty_egg.webp 315w /static/8058f3f26913fea3b6a89a73344fe94a/d869c/salty_egg.webp 630w /static/8058f3f26913fea3b6a89a73344fe94a/38d5d/salty_egg.webp 945w /static/8058f3f26913fea3b6a89a73344fe94a/4eefe/salty_egg.webp 1260w /static/8058f3f26913fea3b6a89a73344fe94a/7c4f2/salty_egg.webp 2048w" sizes="(max-width: 630px) 100vw, 630px" type="image/webp">
```

**Comment by wooorm** [comment]
Hi.

The example you used for `rehype-react` is rather bad btw. I believe it comes from an old blog post that could use some updating. If you have an (hast) AST and want to turn it into React or similar, use [`hast-to-hyperscript`](https://github.com/syntax-tree/hast-to-hyperscript#use).

The AST they generate should in this case not generate an array, but generate a string. See also: https://github.com/wooorm/property-information/commit/acf30dd81942e1c03e5ea4301887307df4c6ba30.

**Comment by yathomasi** [comment]
Hi, 

> The example you used for `rehype-react` is rather bad btw. If you have an (hast) AST and want to turn it into React or similar, use [hast-to-hyperscript](https://github.com/syntax-tree/hast-to-hyperscript#use)

It has been used to support some custom components on markdown. I believe that's the right use case.

> I believe it comes from an old blog post

Yes, it's been a while

> The AST they generate should in this case not generate an array, but generate a string.

Okay, I assumed it to be an array but if it's a string then I think the problem is on `gatsby-transformer-remark` end to generated hast.
