### ISSUE TITLE
problem parse element with ref string

### ISSUE THREAD

**Issue by denisso** [rehypejs/rehype-react#42]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-react": "^7.1.1"

### Link to runnable example

[codesandbox](https://codesandbox.io/s/rehype-react-ref-string-error-17vu35)

### Steps to reproduce

```
import "./styles.css";
import React, { createElement, Fragment, useEffect, useState } from "react";
import { unified } from "unified";
import rehypeParse from "rehype-parse";
import rehypeReact from "rehype-react";

const text = `<button
className="codecopy"
onClick={handlerCopy}
ref={refBtnCopy}
>
{textBthCopy}
</button>`;

function useProcessor(text) {
  const [Content, setContent] = React.useState(Fragment);

  React.useEffect(() => {
    unified()
      .use(rehypeParse, { fragment: true })
      .use(rehypeReact, { createElement, Fragment })
      .process(text)
      .then((file) => {
        setContent(file.result);
      });
  }, [text]);

  return Content;
}

export default function App() {
  return useProcessor(text);
}

```

### Expected behavior

I expected the display without error

### Actual behavior

Unhandled Runtime Error
Error: Function components cannot have string refs. We recommend using useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref

**Comment by denisso** [comment]
My solution make some changes in in function h in [this file](https://github.com/rehypejs/rehype-react/blob/main/lib/index.js)         
```
if (props?.ref) {
    props.ref = null;
}
```

**Comment by wooorm** [comment]
You are not passing html. You are passing jsx, which is javascript and an extension.
This project handles html. Not JSX.

**Comment by denisso** [comment]
thank you for answer [wooorm](https://github.com/wooorm). You're a cool coder, I use your libraries in my personal projects and I like them. But this is the first time I passed this line along with other text, I highlighted the problem specifically for an example.

**Comment by wooorm** [comment]
What do you expect to happen if you'd pass Rust code, as an example, to this project? This project handles HTML: it can't handle Rust. Or, to extend this: what if you'd pass html to a rust compiler? It would crash! Now, html itself doesn't have errors, so the braces you have, aren't actually anything in html: they're an unquoted attribute for html. And html only has strings as attribute values. So this is a string. And your framework (react) throws on strings.

This is a) not a problem here, this project is working as it should, b) an xy problem: don't pass jsx, this project isn't for that, you have some deeper problem you haven't explained yet going on. I can only help you if I know what that root problem is.

**Comment by denisso** [comment]
I understood. Initially, I perform the conversion from markdown to html using remark-rehype. I know about "fenced code blocks" and use it.  I expect to get 

`<p> escaped html </p>`

from a string that for some reason may contain jsx or other code passed to markdown due to inattention, for example (next I will call it "code 1")

```
... marrkdown ...
<button
className="codecopy"
onClick={handlerCopy}
ref={refBtnCopy}
>
{textBthCopy}
</button>
... marrkdown ...
```

I started using plugin "rehype-sanitize" so that "ref" would not be passed to rehype-react. And now if pass the  (code 1) get

```
<p>&lt;button
className="codecopy"
onClick={handlerCopy}
ref={refBtnCopy}</p>
```
How to get code like this

```
<p>
&lt;button
className="codecopy"
onClick={handlerCopy}
ref={refBtnCopy}
&gt
{textBthCopy}
&lt;/butto&gt
</p>
```
I'm making a client server application. server side convert markdown to html 
```
unified()
    .use(remarkParse)
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypePrismCustom )
    .use(rehypeCodeBlock)
    .use(rehypeAhref)
    .use(rehypeStringify, { allowDangerousHtml: true })
```

on client side compile html to React components

```
unified()
    .use(rehypeParse, { fragment: true })
    .use(rehypeSanitize, {
        ...defaultSchema,
        tagNames: [
            ...(defaultSchema.tagNames || []),
            "section",
            "iframe",
        ],

        attributes: {
            ...defaultSchema.attributes,
            "*": ["className"],
            iframe: [
                "width",
                "height",
                "src",
                "title",
                "allow",
                "allowfullscreen",
            ],
        },
    })
    .use(rehypeReact, {
        createElement: React.createElement,
        Fragment: React.Fragment,
        components: {
            section: CodeSection,
        },
    })
```

**Comment by wooorm** [comment]
> I know about "fenced code blocks" and use it

This example you show does not use fenced code. That’s the problem. You need to fence the code. If you use fenced code, you want have this problem.

**Comment by denisso** [comment]
Thank you wroom, I was blown away when I saw how many libraries you support. Let the force be with you.

**Comment by wooorm** [comment]
Thanks Denis :)
