### ISSUE TITLE
Support processing sublist of tags

### ISSUE THREAD

**Issue by Jareechang** [rehypejs/rehype-react#46]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hello,

I am running my personal blog using unified and I am using this plugin.

**The steps are as follow:**

1. Write in Markdown
2. process with unified (+ `rehype-parse` and `rehype-react`)
3. Run `ReactDOM.renderToString`
4. Add onto the site

The problem is I already have an existing unified pipeline that handles markdown with code snippets but this new process integrating with the react components is breaking some things.

I have many code samples on the site using Typescript etc and it thinks those are react components. 

**For Example:**

```ts
Array<string>
```

### Solution

I think it would be great to support a new options - `options.supportedTags` .

**What it will include:** list of tags (ie `['p', 'a', ...]`)

**Type:** Array<string>

**It will have the following behaviours:**

- If there are no tags defined, default to original behaviour (parsing everything)
- If tags are defined, only run the processing on the listed tags

### Alternatives

I mean technically I can pass in all those tags into the `options.components` but that is a pain because every time I write a blog post with snippets using Typescript, I would need to update the list.

I am open to other solutions though.

Let me know I can make a PR for this with tests. 

I am happy to support it (It would be great to have for me) 🙏

**Comment by wooorm** [comment]
Hey! I don’t quite understand what you mean.
Can you share a summary of the two processes you have?

> breaking some things.

Which things?

> I have many code samples on the site using Typescript etc and it thinks those are react components.

Can you explain? Who thinks that?
